### ISSUE TITLE
Examples code

### ISSUE THREAD

**Issue by Leolik** [lytc/react-nested-sortable#37]
Hi, may you please provide code for your examples https://lytc.github.io/react-sortly/#/examples
I want create Multiple Tree, as in your example here https://lytc.github.io/react-sortly/#/examples/multiple-tree
but I can't do it without example code ((

**Comment by lytc** [comment]
Hi Sukochev,
Code is here
https://github.com/lytc/react-sortly/blob/develop/packages/documentation/src/pages/examples/MultipleTree.tsx

Best,
Ly

**Comment by Leolik** [comment]
thx
